[package]
name = "day01"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day01part1"
path = "./day01part1.rs"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
datatest = "0.7"
itertools = "0.10"
