[package]
name = "day16"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "day16"
path = "./day16.rs"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
datatest = "0.8.0"
itertools = "0.14.0"
regex = "1.11.2"
